HEADERS += \
    exceptions/ServerException.h \
    server/BufferManager.h \
    Buffer.h \
    exceptions/BufferException.h \
    exceptions/ProtocolException.h \
    ConnectionHandler.h \
    RequestHandler.h \
    server/ServerConnectionHandler.h \
    client/ClientConnectionHandler.h \
    server/ServerSideRequestHandlerFactory.h \
    server/handler/PushRequestHandler.h \
    server/handler/GetBufferRequestHandler.h \
    server/handler/ServerSideRequestHandler.h \
    server/buffer/HashTableBufferManager.h \
    FixedSizeQueue.h \
    server/BufferServer.h \
    BufferStorageGlobal.h \
    exceptions/BufferStorageException.h \
    exceptions/ClientException.h \
    protocol/Response.h \
    protocol/PushRequest.h \
    protocol/GetBufferResponse.h \
    protocol/GetBufferRequest.h \
    protocol/Request.h \
    protocol/ProtocolMessageFactory.h \
    protocol/ErrorResponse.h \
    protocol/PushResponse.h \
    SignalBuffer.h \
    SignalValue.h \
    client/listener/BlockingListener.h \
    server/buffer/TreeMapBufferManager.h \
    protocol/GetSignalValuesRequest.h \
    protocol/GetSignalValuesResponse.h \
    server/handler/GetSignalValuesRequestHandler.h \
    protocol/ProtocolMessage.h \
    client/BufferClientImplementation.h \
    client/BufferClientImplementationPrivate.h \
    client/BufferClient.h

SOURCES += \
    ConnectionHandler.cpp \
    RequestHandler.cpp \
    server/ServerConnectionHandler.cpp \
    client/ClientConnectionHandler.cpp \
    server/BufferServer.cpp \
    server/ServerSideRequestHandlerFactory.cpp \
    server/handler/PushRequestHandler.cpp \
    server/handler/GetBufferRequestHandler.cpp \
    server/handler/ServerSideRequestHandler.cpp \
    server/buffer/HashTableBufferManager.cpp \
    protocol/GetBufferRequest.cpp \
    protocol/GetBufferResponse.cpp \
    protocol/PushRequest.cpp \
    protocol/Request.cpp \
    protocol/Response.cpp \
    protocol/ErrorResponse.cpp \
    protocol/PushResponse.cpp \
    client/listener/BlockingListener.cpp \
    server/buffer/TreeMapBufferManager.cpp \
    protocol/GetSignalValuesRequest.cpp \
    protocol/GetSignalValuesResponse.cpp \
    server/handler/GetSignalValuesRequestHandler.cpp \
    protocol/ProtocolMessage.cpp \
    protocol/ProtocolMessageFactory.cpp \
    client/BufferClientImplementation.cpp \
    client/BufferClientImplementationPrivate.cpp
